### ISSUE TITLE
Make fn return a promise?

### ISSUE THREAD

**Issue by t0mclaudio** [sindresorhus/chunkify#4]
I was just wondering if there is a benefit to making the `chunkify` function return a Promise? I am thinking of a use case where we pass a large iterable data? I'm sorry if this question is a silly one. 😄

**Comment by sindresorhus** [comment]
It would create more overhead than benefit for most cases. If you really do have a huge data set, you should instead run it in a `worker_thread`. However, since it's an iterable, you could use it with a `for-awaits` loop: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#iterating_over_sync_iterables_and_generators It will still block the main thread, but at least it will give up the main thread for each iteration.
